using System;

public enum SIUpgradeType
{
	InvalidNode = -2,
	Initialize,
	Thruster_Unlock,
	Thruster_Jet,
	Thruster_Prop,
	Thruster_Jet_Duration,
	Thruster_Jet_Accel,
	Thruster_Prop_Duration,
	Thruster_Prop_Speed,
	Thruster_Jet_Tag,
	Thruster_Prop_Knockback,
	Thruster_Fuel_Grounding,
	Thruster_Throttle_Control,
	Stilt_Unlock = 100,
	Stilt_Tag_Tip,
	Stilt_Retractable,
	Stilt_Adjustable_Length,
	Stilt_Retract_Speed,
	Stilt_Max_Length,
	Stilt_Stun_Tip,
	Stilt_Muscle_Fusion,
	Stilt_Short,
	Stilt_Long,
	Stilt_Motorized,
	Stilt_Motorized_Triple,
	Stilt_Turkey_Coma,
	Grenade_Concussion_Unlock = 200,
	Grenade_Antigravity_Unlock,
	Grenade_Concussion_Stun,
	Grenade_Concussion_Radius,
	Grenade_Antigravity_Persists,
	Grenade_Antigravity_Cooldown,
	Grenade_Concussion_Self_Boost,
	Grenade_Concussion_Overcharge,
	Grenade_Antigravity_Pro_Gravity,
	Grenade_Concussion_Impact_Accelerant,
	Grenade_Antigravity_Gravity_Bomb,
	Grenade_Antigravity_Black_Hole,
	Grenade_Holster_Unlock,
	Grenade_Stun_Unlock,
	Grenade_Puller_Unlock,
	Grenade_Disrupter_Unlock,
	Dash_Yoyo_Unlock = 301,
	Dash_Yoyo_Range = 304,
	Dash_Yoyo_Speed,
	Dash_Unused_306,
	Dash_Unused_307,
	Dash_Yoyo_Cooldown,
	Dash_Yoyo_Dynamic,
	Dash_Unused_310,
	Dash_Yoyo_Stun,
	Dash_Yoyo_Tag,
	Dash_Unused_313,
	Dash_Unused_314,
	Platform_Unlock = 400,
	Platform_Cooldown,
	Platform_Duration,
	Platform_Capacity,
	Platform_SpeedBoost,
	Tapteleport_Unlock = 500,
	Tapteleport_Zone,
	Tapteleport_Stealth,
	Tapteleport_Portal_Selection,
	Tapteleport_Keep_Velocity,
	Tapteleport_Infinite_Use,
	Tentacle_Unlock = 600,
	Tentacle_Power_Claw,
	Tentacle_Charge_Rate,
	Tentacle_Efficiency,
	Tentacle_Crawler,
	Tentacle_Strider,
	AirControl_AirJuke_Unlock = 700,
	AirControl_AirJuke_Speed,
	AirControl_AirGrab_Unlock,
	AirControl_AirGrab_Speed,
	AirControl_AirGrab_HoldTime,
	AirControl_Zipline_Unlock,
	AirControl_Zipline_Speed,
	Prototype_SlipMitt = 800,
	Prototype_Wing,
	Prototype_802,
	Prototype_803,
	Prototype_804,
	Prototype_805,
	Blaster_Standard_Unlock = 1000,
	Blaster_Charge_Unlock,
	Blaster_Lobber_Unlock,
	Blaster_PumpDart_Unlock,
	Blaster_MegaCharge_Unlock,
	Blaster_LongBlaster_Unlock
}
